config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: [ :index, :new, :create ]
  end
  resources :reviews, only: [ :show, :edit, :update, :destroy ]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :restaurant_id, presence: true
  validates :rating, presence: true, inclusion: { in: [0, 1, 2, 3, 4, 5] }
  validates_numericality_of :rating
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  def index
    @reviews = Review.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = Restaurant.find(params[:restaurant_id])
    if @review.save
      redirect_to restaurant_path(@review.restaurant)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to review_path(@review)
    else
      render :edit
    end
  end

  def destroy
    @review.destroy
    redirect_to review_path
  end

  private

  def set_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:content, :rating, :restaurant_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>


<!-- app/views/layouts/application.html.erb -->
<head>
  <!-- Add these line for detecting device width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <!-- [...] -->
</head>

app/views/restaurants/_form.html.erb
<%= simple_form_for (@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @restaurant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class="form-group">
      <%= f.input :name %>
    </div>
    <div class="form-group">
      <%= f.input :address %>
    </div>
    <div class="form-group">
      <%= f.input :phone_number %>
    </div>
    <div class="form-group">
      <%= f.input :category %>
    </div>
    <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit <%= @restaurant.name %></h1>

<%= render 'form'%>

<%= link_to restaurants_path, class: 'btn btn-primary' do %>
  <i class="fa fa-history"></i> Back to list
<% end %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<%= link_to new_restaurant_path do %>
  <i class="fa fa-plus"></i> Add a new restaurant
<% end %>

<br>
<br>
<ul id="restaurants">
  <% @restaurants.each do |restaurant| %>
    <li>
      <%= link_to restaurant.name, restaurant_path(restaurant.id) %>
      <%= link_to restaurant_path(restaurant.id), method: :destroy, data: { confirm: "Delete #{restaurant.name}?" } do %>
        <i class="fa fa-trash-o" aria-hidden="true"></i>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<h1>Add a restaurant</h1>

<%= render "form" %>

app/views/restaurants/show.html.erb
<h1 class="well"><%= @restaurant.name %></h1>
<p class="well"><%= @restaurant.category %></p>
<p class="well"><%= @restaurant.address %></p>
<p class="well"><%= @restaurant.phone_number %></p>
<ul class="well">
  Ratings:
  <% @restaurant.reviews.each do |review| %>
    <li><%= review.content %> | <%= review.rating %> <i class="fa fa-star"></i></li>
  <% end %>
</ul>

<%= link_to restaurants_path, class: 'btn btn-primary' do %>
  <i class="fa fa-history"></i>
<% end %>
<%= link_to new_restaurant_review_path(@restaurant.id), class: 'btn btn-primary' do %>
  <i class="fa fa-star"></i>
<% end %>
<%= link_to edit_restaurant_path(@restaurant.id), class: 'btn btn-primary' do %>
  <i class="fa fa-pencil"></i>
<% end %>

app/views/reviews/_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>

    <div class="form-group">
      <%= f.input :content %>
    </div>
    <div class="form-group">
      <%= f.input :rating %>
    </div>
    <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/reviews/new.html.erb
<h1>Add a review</h1>

<%= render "form" %>